FROM fedora:latest
LABEL MAINTAINER Francesco Zanti

#ENV DEBIAN_FRONTEND noninteractive

RUN sudo dnf update -y 

# Install all apps
# The third line is for multi-site config (ping is for testing later)
#RUN apt-get install -y pkg-config
# RUN apt-get install -y   libnss-winbind libpam-winbind 
RUN sudo dnf install -y attr acl samba samba-client samba-common samba-winbind krb5-workstation krb5-libs krb5-server supervisor openldap
#RUN apt-get install -y openvpn inetutils-ping

# Set up script and run
ADD init.sh /init.sh
RUN chmod 755 /init.sh
CMD /init.sh setup
